---
dist: trixie
language: python
python: "3.9"

# Use the new container infrastructure
sudo: true

# Install ansible
addons:
  apt:
    packages:
    - ansible

install:
  # Check ansible version
  - ansible --version

# # Create ansible.cfg with correct roles_path
# - printf '[defaults]\nroles_path=../' >ansible.cfg

  # Install Role from Ansible Galaxy
  - ansible-galaxy install ypsman.packages

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i localhost --syntax-check
  - ansible-playbook tests/test.yml -i localhost
 
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

