---
# tasks file for base packages
- name: Running apt Cache update
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Installing Packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages | default([]) }}"

- name: Remove unwanted Packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop: "{{ packages_remove | default([]) }}"
...
