---
# tasks file for base packages
- name: running apt Cache update
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: installing Packages
  package: name={{ item }} state=present
  with_items: "{{ packages|default([]) }}"

- name: remove unwanted Packages
  package : name={{ item }} state=absent
  with_items: "{{ packages_remove|default([]) }}"
